language: php

php:
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

branches:
  only:
    - master
    - travis

before_install:
  - test "$TRAVIS_PHP_VERSION" != "nightly" || export COMPOSER_FLAGS="$COMPOSER_FLAGS --ignore-platform-reqs"

install:
  - composer install --prefer-source $COMPOSER_FLAGS
  - wget https://scrutinizer-ci.com/ocular.phar -O "$HOME/ocular.phar"

before_script: |
  if (php -m | grep -q -i xdebug); then
    export COVERAGE_FLAGS="--coverage --coverage-xml"
  else
    export COVERAGE_FLAGS=""
  fi

script:
  - vendor/bin/codecept run $COVERAGE_FLAGS

after_script:
  - test "$COVERAGE_FLAGS" == "" || php "$HOME/ocular.phar" code-coverage:upload --format=php-clover tests/_output/coverage.xml

